# This workflow will run eslint on Pushes and Pull Requests

name: ESLint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Repository
      uses: actions/checkout@v3

    - name: Install Node.JS v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
      run: npm ci

    - name: Lint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
